project:
  type: website
  output-dir: docs

website:
  title: "Andrew Kingston"
  favicon: akalysis.png
  site-url: https://andrew-kingston.github.io/
  description: "Healthy ageing, simulated. Colourful epidemiology, minus the beige."
  search: true
  open-graph: true
  twitter-card: true
  repo-url: https://github.com/andrew-kingston/andrew-kingston.github.io
  repo-actions: [issue]

  navbar:
    background: "#0B3D91"
    foreground: light
    logo: akalysis.png
    left:
      - href: index.qmd
        text: Home
      - text: Research
        menu:
          - text: Research Programme
            href: research-programme.qmd
          - text: Publications
            href: publications.qmd
      - text: Learning
        menu:
          - text: Teaching / Training
            href: teaching-training.qmd
          - text: Digital Garden
            href: digital-garden/index.qmd
          - text: Blog
            href: blog/index.qmd
      - text: Collaboration
        menu:
          - text: Consulting
            href: consulting.qmd
          - text: Speaking
            href: speaking.qmd
          - text: Contact
            href: contact.qmd
      - text: About
        menu:
          - text: CV
            href: cv.qmd

page-footer:
  left: "© {{< meta year >}} Andrew Kingston"
  right: "Built with Quarto • Hosted on GitHub Pages"

from: markdown+raw_html+fenced_divs+bracketed_spans+link_attributes

format:
  html:
    theme: cosmo
    css:
      - fonts.css
      - styles.scss
    toc: true
    smooth-scroll: true
    anchor-sections: true
    code-copy: true

execute:
  freeze: auto